---
# tasks file for vector-role
- name: Get Vector setup script
  ansible.builtin.get_url:
    url: "https://repositories.timber.io/public/vector/cfg/setup/bash.rpm.sh"
    dest: "/tmp/bash.rpm.sh"
    mode: '0777'
- name: Run Vector setup script
  become: true
  ansible.builtin.command:
    cmd: "/tmp/bash.rpm.sh"
  changed_when: true
- name: Yum install Vector
  become: true
  ansible.builtin.yum:
    name: vector-0.22.3
    #{{ vector_version }}
    state: installed
- name: Start Vector
  become: true
  ansible.builtin.service:
    name: vector
    state: started
    enabled: true